services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets-please-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: php artisan serve --host=0.0.0.0 --port=8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ticket-please-network

  db:
    image: mysql:8.4.3
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets-please
    networks:
      - ticket-please-network

networks:
  ticket-please-network:
    driver: bridge